<?php

/*
 * Implementation of hook_menu()
 */
function example_menu(){
/* path location (<a href="http://www.url.com/examplepage"
 * title="http://www.url.com/examplepage">http://www.url.com/foo/bar</a> )
 */
    $items['examplepage'] = array(
        // page title
        'title' => 'Page Title Example',
        // describe the page for the menu system.  site visitors will not see this
        'description' => 'Simple custom hook_menu() implementation.',
        // function that is called when visiting the new path
        'page callback' => 'my_page_function',
        // permissions required to view page
        'access arguments' => array('access content'),


    );
    return $items;
}


/*
 * Returns custom content to Drupal
 */
function my_page_function(){
	// Call theme() function, so that Drupal includes the custom-page.tpl.php template
    return theme('my_custom_template');
}

/*
 * Implement hook_theme().
 */
function example_theme(){
    return array(
        'my_custom_template' => array(
            // file name will be custom-page.tpl.php
            'template' => 'custom-page',
        ),
    );
}



/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function example_help($path, $arg){
	switch ($path) {
    case "admin/help#example":
      return '<p>' . t("Displays links to nodes created on this date") . '</p>';
      break;
  }
}
